### ISSUE TITLE
[Improvements] Seems like we have same problems on this boilerplate project

### ISSUE THREAD

**Issue by ArnauKokoro** [IT4Change/boilerplate-frontend#1]
Hi,

I saw your comment on storybook issue and seems like we have same problems.

I have also problem when building: _vue-tsc --noEmit && vite build_

- Have to comment _// "src/**/*.ts"_ from tsconfig.json
- Change _moduleResolution to "bundler"_ to make it work. https://github.com/isaacs/node-lru-cache/pull/323 (waiting for this to be merged)

Thanks!

**Comment by ulfgebhardt** [comment]
![image](https://github.com/IT4Change/boilerplate-frontend/assets/1238238/ff738005-f4de-487f-bab7-372935dc7221)

I get it compiled properly - no problems.

Tho I am not able to view the results due to browser limitations
![image](https://github.com/IT4Change/boilerplate-frontend/assets/1238238/23991814-90f5-48bb-af96-9788cbec3d4c)

Running `npm run preview` - which I presume to be the preview of the build files works fine tho:
![image](https://github.com/IT4Change/boilerplate-frontend/assets/1238238/7735940b-a72d-4482-aba5-d82884e92bf8)

I do not fully get what you want to say to me - can you clarify?
Do you have a solution to the storybook problem?
Can you like your sources or are they closed?

❤️

**Comment by ArnauKokoro** [comment]
I see! It works building on yours. So I think my proble could see that I'm using yarn instead of npm.

Many thanks!

**Comment by ulfgebhardt** [comment]
@ArnauKokoro I switched Technologie a bit more - moved away from `nuxt`, am using `vite` & `vike`. I have a working boilerplate now - closing this issue ❤️
